#\: import TitleBar widgets.titlebar
<TitleBar@Label>:
  size_hint_y: None
  height: 50
  color: 0,0,0,1
  
  canvas.before:
    Rectangle:
      size: self.size
      pos: self.pos
    
    Color:
      rgba: 0.5,0.5,0.5,1
      
<TitleBar2@Label>:
  size_hint_y: None
  height: 50
  color: 0,0,0,1
  
  canvas.before:
    Rectangle:
      size: self.size
      pos: self.pos
    
    Color:
      rgba: 0.5,0.5,0.5,1

